baseURL = 'https://dashiyiqu.dpdns.org/'
defaultContentLanguage = "zh"
languageCode = "zh-Hans"
title = '编程技术｜运维技术｜建站技巧｜后端开发｜前端开发｜知识库｜免费资源'
description = "分享编程技术 Hugo 建站技巧、静态站点 SEO 优化、前端开发经验，帮助开发者打造高性能博客，免费资源。"
theme = 'dream'

# 内容目录配置
# contentDir="content"

enableGitInfo = true
enableRobotsTXT = true

hasCJKLanguage = true

[markup]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

# 代码高亮
[markup.highlight]
noClasses = true
codeFences = true
style = 'dracula'
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
# 网站完全打开前预加载动画
enablePreLoad = true
# 预加载的动画文字, 只有当enablePreLoad=true时生效
textPreLoad   = "AiEDU"

# 布局改为横栏模式，图在右面
# zenMode = true

# 配置每页记录数
paginate = 12
# 是否展示中间分类导航开关
enableCategoryNav = true

# 当亮色时候，选择翡翠绿配色
lightTheme = "emerald"
# 当暗色时候，选择森林配色
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

images = ["img/global-background.jpg"]

author = "AiEDU"
description = "Just do it!"
avatar = "img/personal/avatar.png"
headerTitle = "AiEDU | BLOG"
motto = "AI 赋能，智启教育"

footerBottomText = "知识改变命运，AI改变知识"

rss = true

# utterancesRepo = "88899/hugo-blog"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "aiedu985@gmail.com"

siteStartYear = 2023

favicon = 'img/personal/avatar.png'

# Syntax highlighting
customSyntaxHighlighting = true

# options
# 导航栏吸顶开关
stickyNav = true

# 导航菜单选项
# remove rss
reorderNavItems = ["home", "categories", "tags", "posts", "tools", "docs", "search", "github", "about"]

# 是否折叠显示导航菜单
#collapseNavItems = ["posts", "categories", "tags", "rss"]
# 是否显示默认的封面图
# noDefaultSummaryCover = true

# 是否显示文章目录
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderShares = ["WeChat", "x", "facebook", "whatsapp"]

# https://gohugo.io/templates/embedded/#configure-x-twitter-cards
[params.social]
twitter = "dgdghub"

[params.navItems]
home = { href = "/", icon = "home", title = "首页" }
github = { href = "https://github.com/88899/hugo-blog", icon = "logo-github", title = "GitHub" }
tools = { href = "https://www.518855.xyz", icon = "rocket", title = "导航" }
docs = { href = "https://cici.pp.ua", icon = "documents", title = "文档" }
# me = { href = "https://985188.xyz", icon = "person", title = "About" }

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
# jsDateFormat = "yyyy年MM月dd日，cccc"

# for peht theme
#[params.Author]
#name = "AiEDU"
#avatar = "img/personal/avatar.png"

[services]
[services.googleAnalytics]
ID = "G-7QPNK9FQQL"

[services.disqus]
# shortname = "aiedu-1"

# 多个内容目录映射
[module]
[[module.mounts]]
    source = "content"       # 实际目录：原 content 目录
    target = "content"       # 映射到虚拟 content 目录（保持原路径）

[[module.mounts]]
    source = "global"        # 实际目录：根目录下的 global 目录
    target = "content" # 映射到虚拟 content
